Enhance Find command to be able to use for multiple fields at once.
AY2223S2-CS2103T-F12-3/tp pull request #143
Opened 2023-03-22 09:56 UTC by igezt

Usage e.g.:
find n/Pierce n/Stanley mt/CS2103T
will find all contacts that have either Pierce **or** Stanley in their name and has CS2103T in their modules taken.

Note: Its an either or for the name field because there are multiple names specified.

2023-03-23 07:35 UTC, hansstanley requested changes
Some suggestions to reduce code duplication among other benefits, but the changes compared to what it is now could be quite significant, so up to your discretion.

Overall good effort 👍🏼

2023-03-23 07:35 UTC, hansstanley commented on src/main/java/seedu/address/model/person/fields/Address.java
> +    }
As mentioned in `Person.java`, this method can be abstracted into a `Field` abstract class or interface (same applies for the rest of the fields).

> although if that's too much work I can understand up to your own discretion there's so much work this week and so little time aaaaahhhhhh

2023-03-23 07:35 UTC, hansstanley commented on src/main/java/seedu/address/storage/user/JsonAdaptedUser.java
> +                            @JsonProperty("events") List<JsonAdaptedEvent> events) {
Good catch 👍🏼

2023-03-23 07:47 UTC, igezt commented on src/main/java/seedu/address/logic/commands/FindCommand.java
> +            + "with index numbers.\n"
HAHAHA alright thank you

2023-03-23 07:48 UTC, igezt commented on src/main/java/seedu/address/model/person/PersonContainsKeywordsPredicate.java
> +    }
OOOO GOOD SUGGESTION. THANKS FAM

2023-03-25 16:04 UTC, hansstanley approved these changes
Added some comments on search behaviour that I think are important to consider, otherwise approved so you can merge after.

2023-03-25 16:04 UTC, hansstanley commented on src/main/java/seedu/address/model/person/fields/Field.java
>      }
With reference to the previous comment, this has an OR relationship!

2023-03-25 16:04 UTC, hansstanley commented on src/main/java/seedu/address/model/person/Person.java
> +    public boolean contains(HashMap<PredicateKey, Set<String>> keywords) {
Also might have to consider this when writing tests

2023-03-26 09:17 UTC, merged